'use client';
import { useState } from 'react';
import type { BehavioralComparison } from '@/lib/behavioral-comparison-schema';
export default function DifferentialComparison({ report, onEvent }: { report: BehavioralComparison; onEvent: (id:string)=>void }) {
  const [selected,setSelected]=useState('network');const category=report.categories.find(c=>c.category===selected)!;
  return <section className="panel case-comparison" aria-labelledby="comparison-heading"><p className="panel-kicker">06 / DIFFERENTIAL RESEARCH</p><div className="case-section-heading"><h3 id="comparison-heading">Baseline versus stimulus</h3><span className="case-tag">{report.status} comparison</span></div><p className="case-note">Baseline observes the page. Stimulus reloads it in a fresh browser context and executes bounded agent actions. Both contexts share one sandbox.</p>
    <div className="comparison-categories" role="group" aria-label="Comparison categories">{report.categories.map(c=><button key={c.category} aria-pressed={selected===c.category} onClick={()=>setSelected(c.category)}><strong>{c.category.toUpperCase()}</strong><small>{c.status==='unavailable'?'Unavailable':`${c.added+c.removed+c.changed} changed identities`} · {c.status}</small></button>)}</div>
    <div className="comparison-detail" aria-live="polite"><h4>{category.category.toUpperCase()} comparison</h4>{category.status==='unavailable'?<p className="case-warning">Paired evidence is unavailable. No conclusion about change can be drawn.</p>:<><div className="comparison-counts"><div><strong>{category.baselineCount??'—'}</strong><span>baseline records</span></div><div><strong>{category.stimulusCount??'—'}</strong><span>stimulus records</span></div><div><strong>{category.added}</strong><span>added identities</span></div><div><strong>{category.removed}</strong><span>baseline only</span></div><div><strong>{category.changed}</strong><span>changed measurements / counts</span></div><div><strong>{category.unchanged}</strong><span>unchanged identities</span></div></div>{category.status==='partial'&&<p className="case-warning">Partial comparison: collection or run limitations apply. Baseline-only records do not prove behaviour was removed.</p>}</>}
      <ul className="case-limitations">{category.notes.map((n,i)=><li key={i}>{n}</li>)}</ul>
      {category.metrics.length>0&&<div className="case-table-scroll"><table className="case-event-table"><thead><tr><th scope="col">Metric</th><th scope="col">Baseline</th><th scope="col">Stimulus</th><th scope="col">Delta</th></tr></thead><tbody>{category.metrics.map((m,i)=><tr key={i}><td>{m.name}</td><td>{m.baseline}</td><td>{m.stimulus}</td><td>{m.delta>0?'+':''}{m.delta}</td></tr>)}</tbody></table><div className="case-ref-links">{category.metrics.flatMap(m=>m.references).filter((r,i,all)=>all.findIndex(x=>x.id===r.id)===i).map(r=>r.kind==='event'?<button key={r.id} onClick={()=>onEvent(r.id)}>Inspect {r.id}</button>:<code key={r.id}>{r.id}</code>)}</div></div>}
      {category.differences.length>0?<ul className="comparison-differences">{category.differences.map((d,i)=><li key={i}><strong>{d.value}</strong><span>Baseline {d.baselineCount} → stimulus {d.stimulusCount}</span><div className="case-ref-links">{d.references.map((r,j)=>r.kind==='event'?<button key={j} onClick={()=>onEvent(r.id)}>Inspect {r.id}</button>:<code key={j}>{r.id}</code>)}</div></li>)}</ul>:category.status!=='unavailable'&&<p className="case-empty">No identity or occurrence-count difference was observed in the compared records. Timing metrics may still differ.</p>}
      {category.truncated&&<p className="case-warning">Output is bounded to 40 differing identities and 12 references per identity. Aggregate totals include all compared identities.</p>}
    </div><details className="comparison-method"><summary>Methodology and limitations</summary><p>Methodology {report.methodologyVersion} · {report.excludedEvents} events excluded from browser-run comparison. Snapshot references are paths in the downloaded case JSON.</p><ul className="case-limitations">{report.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul></details>
  </section>;
}
