'use client';
import type { InvestigationCase } from '@/lib/case-schema';
export default function ResearchLoop({result,onEvent}:{result:InvestigationCase;onEvent:(id:string)=>void}){
  const run=result.research;if(!run)return null;
  const evidenceById=new Map(run.evidence.map(e=>[e.id,e]));
  const actionEvent=(actionId:string)=>result.events?.find(e=>e.details.agentActionId===actionId||e.id==='agent-'+actionId);
  return <section className="panel case-research" aria-labelledby="research-heading"><p className="panel-kicker">07 / BOUNDED RESEARCH AGENT</p><div className="case-section-heading"><h3 id="research-heading">Research questions and experiments</h3><span className="case-tag">{run.stopReason.replaceAll('_',' ')}</span></div><p className="case-note">The agent observes evidence, proposes a question and hypothesis, selects a safe browser tool, and reassesses its result. Model assessments are qualitative interpretations, not verified causal findings.</p>
    {run.providerFailure&&<p className="case-warning">Provider output failure: {run.providerFailure.replaceAll('_',' ')}. No successful action is inferred from an unusable response.</p>}
    <div className="comparison-counts"><div><strong>{run.usage.experiments} / {run.budgets.maxExperiments}</strong><span>experiments</span></div><div><strong>{run.usage.toolCalls} / {run.budgets.maxToolCalls}</strong><span>dispatched browser tools</span></div><div><strong>{run.usage.modelTurns} / {run.budgets.maxModelTurns}</strong><span>provider turns</span></div><div><strong>{(run.usage.runtimeMs/1000).toFixed(1)} / {run.budgets.maxRuntimeMs/1000} s</strong><span>agent loop runtime</span></div><div><strong>{run.budgets.maxOutputAllowance}</strong><span>maximum provider output tokens per turn</span></div><div><strong>{run.evidence.length} / {run.budgets.maxEvidence}</strong><span>retained research evidence</span></div></div>
    {!run.iterations.length?<p className="case-empty">No valid research assessment was recorded before the agent stopped.</p>:<ol className="research-iterations">{run.iterations.map(step=><li key={step.id}><p className="case-tag">{step.origin} assessment · {step.status.replaceAll('_',' ')}</p><h4>{step.question}</h4><p>{step.hypothesis}</p><p className="case-note">Selected tool: {step.selectedTool} · Result: {step.resultStatus}</p><p>{step.evaluation}</p><div className="case-ref-links">{step.actionId&&actionEvent(step.actionId)&&<button onClick={()=>onEvent(actionEvent(step.actionId!)!.id)}>Inspect action {step.actionId}</button>}</div><details><summary>Inspect referenced evidence ({step.evidenceIds.length})</summary>{step.evidenceIds.map(id=>{const e=evidenceById.get(id);return <div className="research-evidence" key={id}><strong>{id}</strong>{e?<><p>{e.description}</p>{e.eventId && (result.events?.some(event=>event.id===e.eventId)?<button className="case-button" onClick={()=>onEvent(e.eventId!)}>Inspect recorded event</button>:<p>Source event was not retained in the exported timeline.</p>)}{e.sha256&&<code>Snapshot SHA-256: {e.sha256}</code>}{e.excerpt!==undefined&&<><p className="case-note">Untrusted text excerpt, bounded to 1200 characters; export redaction may alter it.</p><pre className="mono wrap">{e.excerpt}</pre></>}</>:<p>Referenced evidence is not retained.</p>}</div>;})}</details></li>)}</ol>}
    <p className="case-note">Stop reason is the recorded loop outcome. “Evidence sufficient” reflects the model’s bounded task assessment. A finish decision can also stop because no useful experiment remains. Browser policy and collection limits still apply.</p>
  </section>;
}
