import type { Command, Sandbox } from "@vercel/sandbox";
import type { EbpfProbeResult } from "./ebpf-probe";

export const MAX_PROCESSES = 200;
export const MAX_NETWORK_OBSERVATIONS = 500;
export const MAX_FILESYSTEM_OBSERVATIONS = 500;
const ROOT = "/tmp/kraxxdeceit-browser";

export type ProcessObservation = { pid:number; ppid:number; executable:string; command:string; startTimeMs?:number; state:string };
export type NetworkObservation = { protocol:string; localAddress:string; localPort:number; destinationIp:string; destinationPort:number; state:string; pid?:number; timestampMs:number };
export type FilesystemObservation = { path:string; kind:"created"|"modified"; sizeBytes:number; timestampMs:number };
export type TelemetrySnapshot = { timestampMs:number; processes:ProcessObservation[]; network:NetworkObservation[]; filesystem:FilesystemObservation[]; truncated:string[] };
export type SystemEvent = { timestampMs:number; action:string; details:Record<string,string> };
export type TelemetryCollection = {
  mode?:"snapshot"|"stream"; eventCount?:number; truncated?:boolean;
  streamEvents?:Array<{id:string;timestampMs:number;source:"browser"|"network"|"system"|"agent";action:string;details:Record<string,string>;phase?:string;trafficScope?:string;observedAtMs?:number}>;
  streamRelationships?:Array<{id:string;sourceEventId:string;targetEventId:string;type:"same_destination"|"temporally_related"|"associated_process"|"post_action_observation"|"pre_existing"|"supports_action_hypothesis";label:string}>;
  streamProcesses?:Array<ProcessObservation&{firstSeen:number;lastSeen:number;status:"running"|"exited"}>;
  streamSockets?:Array<NetworkObservation&{firstSeen:number;lastSeen:number;process_identity:string}>;
  providers:Array<{name:string;available:boolean;reason?:string}>; startedAtMs:number; finishedAtMs:number;
  snapshotA:TelemetrySnapshot; snapshotB:TelemetrySnapshot; baselineSnapshot?:TelemetrySnapshot; agentStartSnapshot?:TelemetrySnapshot;
  processes:ProcessObservation[]; network:NetworkObservation[]; filesystem:FilesystemObservation[];
  events:SystemEvent[]; ebpf:EbpfProbeResult; truncationMarkers:string[];
};
export interface TelemetryProvider { readonly name:string; start():Promise<void>; snapshot():Promise<TelemetrySnapshot>; stop():Promise<void>; collect():Promise<TelemetryCollection> }

const SCRIPT = String.raw`
const fs=require('node:fs'),path=require('node:path');const ROOT='/tmp/kraxxdeceit-browser',START=Date.now(),MAX_P=200,MAX_N=500,MAX_F=500;
const ebpf=require(ROOT+'/ebpf-probe.cjs'),stopPath=ROOT+'/telemetry-stop',reqPath=ROOT+'/telemetry-snapshot-request',resPath=ROOT+'/telemetry-snapshot-response';
let prevP=new Map(),prevN=new Set(),seenP=new Map(),seenN=new Map(),seenF=new Map(),events=[],truncated=new Set(),snapshots=[],allFs=[];
function recordEvent(event){if(events.length<1000)events.push(event);else truncated.add('system_event_limit')}
function addr(v,v6){try{const [a,p]=v.split(':');let ip;if(v6){const b=Buffer.from(a,'hex'),x=[];for(let i=0;i<16;i+=4)x.push(b.readUInt32LE(i).toString(16));ip=x.join(':')}else ip=Buffer.from(a,'hex').reverse().join('.');return {ip,port:parseInt(p,16)}}catch{return {ip:'unknown',port:0}}}
function take(now){const pids=[];try{pids.push(...fs.readdirSync('/proc').filter(x=>/^\d+$/.test(x)).map(Number).sort((a,b)=>a-b))}catch{}const owners=new Map();for(const pid of pids){try{for(const fd of fs.readdirSync('/proc/'+pid+'/fd'))try{const m=fs.readlinkSync('/proc/'+pid+'/fd/'+fd).match(/^socket:\[(\d+)\]$/);if(m)owners.set(m[1],pid)}catch{}}catch{}}
const ps=[];for(const pid of pids){if(ps.length>=MAX_P){truncated.add('process_limit');break}try{const raw=fs.readFileSync('/proc/'+pid+'/stat','utf8'),end=raw.lastIndexOf(')'),a=raw.slice(end+2).trim().split(/\s+/),command=raw.slice(raw.indexOf('(')+1,end);let exe='';try{exe=fs.readlinkSync('/proc/'+pid+'/exe').slice(0,512)}catch{}let bt=0,up=0;try{bt=Number(fs.readFileSync('/proc/stat','utf8').match(/^btime (\d+)/m)?.[1])||0;up=Number(fs.readFileSync('/proc/uptime','utf8').split(/\s+/)[0])}catch{}const item={pid,ppid:Number(a[1])||0,executable:exe,command:command.slice(0,128),...(a[19]?{startTimeMs:Math.round((bt+up-Number(a[19])/100)*1000)}:{}),state:(a[0]||'?').slice(0,1)};ps.push(item);if(!seenP.has(pid)){if(seenP.size<MAX_P)seenP.set(pid,item);else truncated.add('process_limit')}}catch{}}
const ns=[];for(const f of ['tcp','tcp6','udp','udp6']){let rows=[];try{rows=fs.readFileSync('/proc/net/'+f,'utf8').trim().split('\n').slice(1)}catch{}for(const row of rows){if(ns.length>=MAX_N){truncated.add('network_limit');break}const c=row.trim().split(/\s+/);if(c.length<10)continue;const l=addr(c[1],f.endsWith('6')),r=addr(c[2],f.endsWith('6')),state=c[3]==='0A'?'LISTEN':c[3]==='01'?'ESTABLISHED':c[3],item={protocol:f.startsWith('tcp')?'tcp':'udp',localAddress:l.ip,localPort:l.port,destinationIp:r.ip,destinationPort:r.port,state,...(owners.has(c[9])?{pid:owners.get(c[9])}:{}),timestampMs:now-START};ns.push(item);const k=[item.protocol,item.localAddress,item.localPort,item.destinationIp,item.destinationPort,item.state,item.pid||''].join('|');if(!prevN.has(k)){if(seenN.size<MAX_N)seenN.set(k,item);else truncated.add('network_limit');if(state==='ESTABLISHED'&&r.port)recordEvent({timestampMs:item.timestampMs,action:'system.network_connection',details:{protocol:item.protocol,destinationIp:r.ip,destinationPort:String(r.port),...(item.pid?{pid:String(item.pid)}:{})}})}}}
const next=new Map(ps.map(x=>[x.pid,x]));for(const [pid,x]of next)if(!prevP.has(pid))recordEvent({timestampMs:now-START,action:'system.process_started',details:{pid:String(pid),ppid:String(x.ppid),command:x.command,executable:x.executable,...(x.startTimeMs?{startTimeMs:String(x.startTimeMs)}:{})}});for(const [pid,x]of prevP)if(!next.has(pid))recordEvent({timestampMs:now-START,action:'system.process_exited',details:{pid:String(pid),command:x.command,executable:x.executable}});prevP=next;prevN=new Set(ns.map(x=>[x.protocol,x.localAddress,x.localPort,x.destinationIp,x.destinationPort,x.state,x.pid||''].join('|')));
const fsobs=[];function walk(d,n){if(n>3||seenF.size>=MAX_F){if(seenF.size>=MAX_F)truncated.add('filesystem_limit');return}let es=[];try{es=fs.readdirSync(d,{withFileTypes:true})}catch{return}for(const e of es){if(seenF.size>=MAX_F){truncated.add('filesystem_limit');break}if(e.name.startsWith('telemetry-')||e.name==='ebpf-probe.cjs')continue;const q=path.join(d,e.name);try{const st=fs.statSync(q);if(st.isDirectory())walk(q,n+1);else{const rel=q.slice(ROOT.length),old=seenF.get(rel);if(!old||old!==st.mtimeMs){const change={path:rel.slice(0,512),kind:old?'modified':'created',sizeBytes:st.size,timestampMs:now-START};fsobs.push(change);if(allFs.length<MAX_F)allFs.push(change);else truncated.add('filesystem_limit');seenF.set(rel,st.mtimeMs)}}}catch{}}}walk(ROOT,0);return {timestampMs:now-START,processes:ps,network:ns.slice(0,MAX_N),filesystem:fsobs.slice(0,MAX_F),truncated:[...truncated]}}
function save(){const a=snapshots[0],b=snapshots[1]||a,filesystem=[...new Map(allFs.map(x=>[x.path,x])).values()].slice(0,MAX_F);fs.writeFileSync(ROOT+'/telemetry.json',JSON.stringify({providers:[{name:'procfs',available:true},{name:'socket-table',available:true},{name:'ebpf-probe',available:!!ebpf.available,...(!ebpf.available?{reason:ebpf.reason}:{})}],startedAtMs:START,finishedAtMs:Date.now(),snapshotA:a,snapshotB:b,processes:[...seenP.values()].slice(0,MAX_P),network:[...seenN.values()].slice(0,MAX_N),filesystem,events,ebpf,truncationMarkers:[...truncated]}))}
snapshots[0]=take(Date.now());fs.writeFileSync(ROOT+'/telemetry-snapshot-a.json',JSON.stringify(snapshots[0]));const timer=setInterval(()=>{const s=take(Date.now());snapshots[1]=s;if(fs.existsSync(reqPath)){try{fs.writeFileSync(resPath,JSON.stringify(s));fs.unlinkSync(reqPath)}catch{}}if(fs.existsSync(stopPath)){clearInterval(timer);save();process.exit(0)}},250);process.on('SIGTERM',()=>{clearInterval(timer);save();process.exit(0)});
`;
export const PROCFS_TELEMETRY_SCRIPT = SCRIPT;

export class ProcfsTelemetryProvider implements TelemetryProvider {
  readonly name:string="procfs+socket-table"; private command?:Command; private startedAtMs=0; private snapshotA?:TelemetrySnapshot; private latestSnapshot?:TelemetrySnapshot; private readonly requestedSnapshots:TelemetrySnapshot[]=[]; private stopped=false;
  constructor(private readonly sandbox:Sandbox){}
  async start(){this.startedAtMs=Date.now();await this.sandbox.mkDir(ROOT).catch(()=>undefined);const controls=['telemetry-stop','telemetry-snapshot-request','telemetry-snapshot-response','telemetry.json','telemetry-snapshot-a.json'];await this.sandbox.runCommand({cmd:'node',args:['-e',`const fs=require('node:fs');for(const name of ${JSON.stringify(controls)})try{fs.unlinkSync(${JSON.stringify(ROOT)}+'/'+name)}catch{}`],timeoutMs:3000}).catch(()=>undefined);const {EBF_PROBE_SCRIPT}=await import('./ebpf-probe');await this.sandbox.writeFiles([{path:`${ROOT}/ebpf-probe.cjs`,content:`module.exports=(()=>{${EBF_PROBE_SCRIPT}\n})()`},{path:`${ROOT}/telemetry-provider.cjs`,content:SCRIPT}]);this.command=await this.sandbox.runCommand({cmd:'node',args:[`${ROOT}/telemetry-provider.cjs`],detached:true,timeoutMs:160_000});this.snapshotA=await this.read(`${ROOT}/telemetry-snapshot-a.json`,8000) as unknown as TelemetrySnapshot;}
  async snapshot(){if(this.stopped)throw new Error('Telemetry provider is stopped.');await this.sandbox.runCommand({cmd:'node',args:['-e',`try{require('fs').unlinkSync('${ROOT}/telemetry-snapshot-response')}catch{}`]}).catch(()=>undefined);await this.sandbox.writeFiles([{path:`${ROOT}/telemetry-snapshot-request`,content:String(Date.now())}]);this.latestSnapshot=await this.read(`${ROOT}/telemetry-snapshot-response`,4000) as unknown as TelemetrySnapshot;this.requestedSnapshots.push(this.latestSnapshot);return this.latestSnapshot;}
  async stop(){if(this.stopped)return;this.stopped=true;await this.sandbox.writeFiles([{path:`${ROOT}/telemetry-stop`,content:'stop'}]);await this.command?.wait();}
  async collect():Promise<TelemetryCollection>{const raw=await this.read(`${ROOT}/telemetry.json`,5000) as unknown as TelemetryCollection;if(!this.snapshotA)throw new Error('Telemetry snapshot A is unavailable.');const baselineSnapshot=this.requestedSnapshots[1]?this.requestedSnapshots[0]:undefined;const agentStartSnapshot=this.requestedSnapshots[1]??this.requestedSnapshots[0];return {...raw,startedAtMs:this.startedAtMs,snapshotA:this.snapshotA,...(baselineSnapshot?{baselineSnapshot}:{}),...(agentStartSnapshot?{agentStartSnapshot}:{})};}
  private async read(path:string,timeout:number){const until=Date.now()+timeout;while(Date.now()<until){const b=await this.sandbox.readFileToBuffer({path}).catch(()=>null);if(b){try{return JSON.parse(b.toString('utf8')) as Record<string,unknown>}catch{}}await new Promise(r=>setTimeout(r,100))}throw new Error(`Sandbox telemetry timed out waiting for ${path.split('/').pop()}.`)}
}
export class SocketTelemetryProvider extends ProcfsTelemetryProvider { readonly name:string="procfs-socket-table"; }
export class EbpfTelemetryProvider { readonly name="ebpf-probe-only"; async probe(result:EbpfProbeResult){return result;} }
