import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Using KraxxDeceit', description: 'A guide to controlled research, evidence exports and private cases.' };
export default function Guide() {
  return <main className="demo-shell"><a className="case-home-link" href="/">KraxxDeceit / research guide</a>
    <section className="panel"><p className="panel-kicker">PUBLIC RESEARCH RELEASE</p><h1>Start with recorded behavior.</h1><p>KraxxDeceit runs fixed synthetic browser experiments in disposable sandboxes and connects observations to their evidence. It is a research instrument; findings are bounded hypotheses rather than a verdict that a website is malicious.</p><div className="case-actions"><a className="primary-cta" href="/demo">OPEN CONTROLLED DEMO</a><a className="case-button" href="/experiments">REPEATED STUDIES</a><a className="case-button" href="/workspace">PRIVATE CASES</a></div></section>
    <section className="panel"><h2>Your first case</h2><ol><li>Open the controlled demo and choose the injection or neutral fixture.</li><li>Keep deterministic research selected. It reads the fixed page and takes a screenshot without calling an AI model.</li><li>Inspect the timeline, evidence graph, comparison and methodology limits.</li><li>Download the case JSON for full recorded evidence, or PDF/Markdown/ZIP for review.</li></ol><p>Optional free AI is experimental and can fail provider or evidence-validation checks. A successful deterministic case does not demonstrate AI resistance to prompt injection. Arbitrary public URL investigations are disabled.</p></section>
    <section className="panel"><h2>Repeated studies</h2><p>Create a study on /experiments. Four explicit steps follow injection → neutral → neutral → injection, or the inverse. Completed runs must have compatible execution metadata and matching recorded digests. This describes fixture and collector repeatability, without a statistical significance or causal claim.</p><p>Admission allows three runs per client per ten minutes, one concurrent per client and three globally. The fourth step can require waiting. Export partial study JSON to preserve progress before closing or reloading the tab; studies are not automatically saved to the server.</p></section>
    <section className="panel"><h2>Private cases and evidence handling</h2><p>The public demo needs no account. Private accounts are provisioned by the project owner during this controlled release. Sign in to save a case explicitly, open it later, or delete its saved row. Cases are immutable; there are no public case links or whole-study server storage.</p><p>Importing and exporting evidence happens locally in your browser. Choosing Save privately uploads the case to your authenticated workspace. Saved rows remain until deleted or the account is removed; provider backups follow provider policies. Session cookies are HTTP-only and private access is enforced server-side and by database ownership policies.</p><p>Review evidence before sharing: exports are not automatically anonymized. Matching case digests and ZIP checksums detect changes; they do not authenticate imported claims. Cases are limited to 3 MiB; study JSON to 13 MiB. Private storage permits 20 cases/20 MiB per account, within a global 200-case/100 MiB payload cap.</p></section>
    <section className="panel"><h2>Limits and support</h2><p>Missing or truncated telemetry does not establish absence of behavior. Availability depends on the sandbox, Redis, hosting and database services. Health checks measure application liveness, not successful research or upstream readiness.</p><p>For a non-sensitive bug report, use the <a href="https://github.com/Basilmellow/KraxxDeceit/issues" target="_blank" rel="noreferrer">project issue tracker</a>. Do not post passwords, tokens or private case evidence. Review the <a href="https://github.com/Basilmellow/KraxxDeceit" target="_blank" rel="noreferrer">source and delivery records</a> for architecture and verification details.</p></section>
  </main>;
}
